pipeline {
    agent any

    stages {
        stage('Docker Compose Build') {
            steps {
                bat """
                    docker-compose -f docker-compose.yml build
                """
            }
        }
    }
}
