pipeline {
    agent any

    stages {
        stage('Docker Compose Build') {
            steps {
                bat """
                    docker-compose -f carpeta/proyectodocker/proyectodocker/docker-compose.yml build
                """
            }
        }
    }

    post {
        always {
            echo " Limpiando contenedores e imágenes creadas por el pipeline..."

            bat """
                docker rm -f full-stack-env || echo "Contenedor no existe, saltando..."
            """
            bat """
                docker rmi -f proyecto-docker:dev-completo || echo "Imagen no existe, saltando..."
            """
            echo " Limpieza completada"
        }
    }
}
